### ISSUE TITLE
'areas' glyph not being created

### ISSUE THREAD

**Issue by tderkert** [huertatipografica/HTLetterspacer#31]
I get an error when i run 'HT LetterSpacer UI' with createProofGlyph set to True. I have installed Modules in Glyphs preferences. Is this a bug or am I missing some plugins for it to work?

```
Start
Config file exists
End

\c\

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/vanilla/vanillaBase.py", line 196, in action_
    self.callback(sender)
  File "HT_LetterSpacer_UI.py", line 133, in dialogCallback
    self.spaceMain()
  File "HT_LetterSpacer_UI.py", line 224, in spaceMain
    self.engine.createAreasGlyph(self.font, self.mySelection[0],self.layerID, [lpolygon, rpolygon])
  File "./HT_LetterSpacer_lib.py", line 118, in createAreasGlyph
    drawArea(origen, f['areas'], margins[0])
  File "./HT_LetterSpacer_lib.py", line 82, in drawArea
    pen = destination.getPen()
  File "/Library/Python/2.7/site-packages/robofab/objects/objectsBase.py", line 1446, in getPen
    return SegmentToPointPen(self.getPointPen())
  File "/Users/teddyderkert/Library/Application Support/Glyphs/Scripts/objectsGS.py", line 661, in getPointPen
    from GSPen import GSPointPen
ImportError: No module named GSPen
```

**Comment by schriftgestalt** [comment]
What version of Glyphs do you have? And can you update the objectsGS.py file to the latest version?

**Comment by tderkert** [comment]
I have the latest Glyphs version as of today, Version 2.4 (939), non cutting edge. 
@schriftgestalt I just got it working by moving `objectsGS.py` and `GSPen.py` from your scripts-repo(pulled the latest) to the root of the script-folder. Otherwise I keep your scripts in a sub-directory to keep organized.

Is this they way I should do it?

**Comment by schriftgestalt** [comment]
This is as it should be.

**Comment by tderkert** [comment]
@schriftgestalt Great. Thanks for the help.

**Comment by etunni** [comment]
**I have a problem when I run "HT Letterspacer UI"**

Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "./HT_LetterSpacer_lib.py", line 19, in <module>
    from objectsGS import *
  File "/Users/etunni/Library/Application Support/Glyphs/Scripts/objectsGS.py", line 13, in <module>
    from robofab.objects.objectsBase import BaseFont, BaseKerning, BaseGroups, BaseInfo, BaseFeatures, BaseLib,\
  File "/Library/Python/2.7/site-packages/robofab/objects/objectsBase.py", line 29, in <module>
    from fontTools.pens.areaPen import AreaPen
ImportError: No module named areaPen

**Comment by schriftgestalt** [comment]
Do you have the latest versions of fonttools?

**Comment by etunni** [comment]
Yes, I updated all modules from Glyphs app.

**Comment by tderkert** [comment]
@etunni have you tried the thing I did above?

**Comment by etunni** [comment]
@tderkert @schriftgestalt I did but don't work for me.
