### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by schriftgestalt** [huertatipografica/HTLetterspacer#40]
I got this traceback from a user:
```
Traceback (most recent call last):

  File "/Library/Python/2.7/site-packages/vanilla/vanillaBase.py", line 214, in action_
    self.callback(sender)

  File "HT_LetterSpacer_UI.py", line 132, in dialogCallback
    self.engine.width = float(self.w.width.get())

ValueError: could not convert string to float: t
```

**Comment by andrestelex** [comment]
It might be because writing weird things on UI fields
