### ISSUE TITLE
What's the problem?

### ISSUE THREAD

**Issue by Andrea991993** [huertatipografica/HTLetterspacer#51]
Traceback (most recent call last):
  File "HT_LetterSpacer.py", line 8, in <module>
    import HT_LetterSpacer_script
  File "/Users/andrea/Library/Application Support/Glyphs/Scripts/HT_LetterSpacer_script.py", line 23, in <module>
    from objectsGS import *
  File "GlyphsApp/objectsGS.py", line 13, in <module>
    from robofab import RoboFabError, RoboFabWarning, ufoLib
  File "/Library/Python/2.7/site-packages/robofab/ufoLib.py", line 38, in <module>
    from robofab.glifLib import GlyphSet, READ_MODE, WRITE_MODE
  File "/Library/Python/2.7/site-packages/robofab/glifLib.py", line 19, in <module>
    from robofab.pens.pointPen import AbstractPointPen
  File "/Library/Python/2.7/site-packages/robofab/pens/pointPen.py", line 145, in <module>
    from fontTools.pens.basePen import AbstractPen
  File "/Library/Python/2.7/site-packages/fontTools/__init__.py", line 1, in <module>
    from fontTools.misc.py23 import *
  File "/Library/Python/2.7/site-packages/fontTools/misc/__init__.py", line 3, in <module>
    from fontTools.misc.py23 import *
  File "/Library/Python/2.7/site-packages/fontTools/misc/py23.py", line 6, in <module>
    from contextlib import redirect_stderr, redirect_stdout
ImportError: cannot import name redirect_stderr

**Comment by juandelperal** [comment]
Hi @Andrea991993
This is because a new version of fontools isn't compatible with Glyphs.
Please replace the `Scripts/fonttools` folder for the version in https://github.com/fonttools/fonttools/releases/tag/3.44.0 


FYI, the last version of fonttools that is compatible with python2.7 is https://github.com/fonttools/fonttools/releases/tag/3.44.0

_Originally posted by @anthrotype in https://github.com/huertatipografica/HTLetterspacer/issues/50#issuecomment-522563325_

**Comment by Andrea991993** [comment]
hi, i tried a replace fonttools but the problem persists.

Traceback (most recent call last):
  File "HT_LetterSpacer_UI.py", line 8, in <module>
    import HT_LetterSpacer_script
  File "/Users/andrew/Library/Application Support/Glyphs/Scripts/HT_LetterSpacer_script.py", line 23, in <module>
    from objectsGS import *
  File "GlyphsApp/objectsGS.py", line 13, in <module>
    from robofab import RoboFabError, RoboFabWarning, ufoLib
  File "/Library/Python/2.7/site-packages/robofab/ufoLib.py", line 38, in <module>
    from robofab.glifLib import GlyphSet, READ_MODE, WRITE_MODE
  File "/Library/Python/2.7/site-packages/robofab/glifLib.py", line 19, in <module>
    from robofab.pens.pointPen import AbstractPointPen
  File "/Library/Python/2.7/site-packages/robofab/pens/pointPen.py", line 145, in <module>
    from fontTools.pens.basePen import AbstractPen
ImportError: No module named fontTools.pens.basePen

**Comment by Andrea991993** [comment]
This after replace fontTools and Robofab:

Traceback (most recent call last):
  File "HT_LetterSpacer_UI.py", line 8, in <module>
    import HT_LetterSpacer_script
  File "/Users/andrew/Library/Application Support/Glyphs/Scripts/HT_LetterSpacer_script.py", line 23, in <module>
    from objectsGS import *
  File "GlyphsApp/objectsGS.py", line 13, in <module>
    from robofab import RoboFabError, RoboFabWarning, ufoLib
ImportError: No module named robofab

**Comment by juandelperal** [comment]
You should copy the folder located in:
fonttools-3.44.0/Lib/fontTools

Best

**Comment by Andrea991993** [comment]
Hi, i did it but i have this error now:


Traceback (most recent call last):
  File "HT_LetterSpacer_UI.py", line 8, in <module>
    import HT_LetterSpacer_script
  File "/Users/andrew/Library/Application Support/Glyphs/Scripts/HT_LetterSpacer_script.py", line 26, in <module>
    from defaultConfigFile import *
  File "/Users/andrew/Library/Application Support/Glyphs/Scripts/defaultConfigFile.py", line 2
    
    ^
SyntaxError: invalid syntax


Thank u very much for help me.

**Comment by juandelperal** [comment]
<img width="242" alt="Screen Shot 2019-09-02 at 11 57 14" src="https://user-images.githubusercontent.com/2414972/64122763-e0098280-cd78-11e9-92d2-9448bf82c86e.png">
@Andrea991993 please keep the files inside its folders
