### ISSUE TITLE
ValueError: could not convert string to float: 'New Value'

### ISSUE THREAD

**Issue by thommilson** [huertatipografica/HTLetterspacer#66]
I'm getting this error is the macro panel in Glyphs 3. Not sure what I'm doing wrong.

Traceback (most recent call last):
  File "HT_LetterSpacer_UI.py", line 15
    HT_LetterSpacer_script.HTLetterspacerScript(ui=True)
  File "HT_LetterSpacer_script.py", line 552, in __init__
    self.getParams()
  File "HT_LetterSpacer_script.py", line 567, in getParams
    setattr(self.engine, param, float(customParam))
ValueError: could not convert string to float: 'New Value'

Any help would be appreciated.

**Comment by sebsan** [comment]
I am getting this error

Config file exists

Traceback (most recent call last):
  File "HT_LetterSpacer_UI.py", line 15
    HT_LetterSpacer_script.HTLetterspacerScript(ui=True)
  File "HT_LetterSpacer_script.py", line 544, in __init__
    self.config = readConfig(self.master.name)
  File "HT_LetterSpacer_script.py", line 232, in readConfig
    newline[4] = float(newline[4])
ValueError: could not convert string to float: 'H'
