### ISSUE TITLE
HT Letterspacer not working on my file — what am I doing wrong?

### ISSUE THREAD

**Issue by szakoba** [huertatipografica/HTLetterspacer#69]
Hello, 

I'm new to HT Letterspacer and am trying to use it for the first time. I think I set up everything just as the instructions said: custom parameters in every master and a configuration script with the same name as the glyphs file in the same location.

When I open HT Letterspacer form Script > HT Letterspacer > HT Letterspacer UI, it opens, but when I use it, it gives a zero or negative side bearings that don't change no matter what I put as the values. The HT Letterspacer Manager doesn't open and shows a dialog:

```
A plugin caused a crash

The Plugin HTLSManager.glyphsPlugin has caused a crash. Please update it by opening the Plugin Manager or re-downloading it from the original source.

Details:
Traceback (most recent call last):

  File "GlyphsApp/GlyphsApp/__init__.py", line 1455, in callback_

  File "plugin.py", line 48, in showWindow_
    self.parameters_dict = {
                           ^

  File "plugin.py", line 50, in <dictcomp>
    "paramArea": int(master.customParameters["paramArea"] or 400),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ValueError: invalid literal for int() with base 10: 'New Value'

App:3.2-3176 Plugin:0.1-1 System:13.2.0
```

It works fine when I open the example file, although Show HT Letterspacer Areas doesn't work there either. I'd be grateful for any guide for a baby.... I have next to no experience with scripting. Thanks

**Comment by szakoba** [comment]
OKAY I FIGURED IT OUT :))) But you should have a look at what the issue is: it was the metrics filters. I had two different metrics for x-Height set in the masters panel - one for lowercase letters and the other one for small caps.

so it was like this:

Metrics type: x-Height / Scope: Case is not Smallcaps
Metrics type: x-Height / Custom name: sc-Height / Scope: Case is Smallcaps

This may have caused the script to get confused. I got rid of the different x-heights and it works perfect now.

**Comment by schriftgestalt** [comment]
(You don’t need to add a filter to the default x-height. Having the filter on the small cap height is enough)
